# Generated by Django 5.0.3 on 2024-03-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mülleimer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hatSensor', models.BooleanField(default=False)),
                ('standort', models.CharField(max_length=100)),
            ],
        ),
    ]
