# Generated by Django 5.0.3 on 2024-03-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binnetapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mülleimer',
            name='standort',
        ),
        migrations.AddField(
            model_name='mülleimer',
            name='len',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mülleimer',
            name='lon',
            field=models.FloatField(default=0.0),
        ),
    ]
