# Generated by Django 5.0.3 on 2024-03-06 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binnetapp', '0002_remove_mülleimer_standort_mülleimer_len_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mülleimer',
            old_name='len',
            new_name='lat',
        ),
    ]
