# Generated by Django 5.0.2 on 2024-03-07 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binnetapp', '0003_rename_len_mülleimer_lat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messung',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mülleimer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binnetapp.mülleimer')),
            ],
        ),
    ]
