# Generated by Django 5.0.2 on 2024-03-08 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binnetapp', '0004_messung'),
    ]

    operations = [
        
        migrations.RenameModel(
            old_name='Mülleimer',
            new_name='Bin',
        ),
        migrations.RenameField(
            model_name='bin',
            old_name='hatSensor',
            new_name='hasSensor',
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binnetapp.bin')),
            ],
        ),
        migrations.DeleteModel(
            name='Messung',
        ),
    ]
