# Generated by Django 5.0.2 on 2024-03-10 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binnetapp', '0005_rename_hatsensor_bin_hassensor_rename_mülleimer_bin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bin',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='bin',
            old_name='lon',
            new_name='longitude',
        ),
    ]
