# Generated by Django 5.0.2 on 2024-03-24 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binnetapp', '0011_alter_bin_color_alter_measurement_measuredate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='measureDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 24, 10, 48, 14, 377418, tzinfo=datetime.timezone.utc)),
        ),
    ]
