# Generated by Django 5.0.3 on 2024-03-25 15:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binnetapp', '0012_alter_measurement_measuredate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bin',
            name='color',
        ),
        migrations.AlterField(
            model_name='measurement',
            name='measureDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 25, 15, 17, 18, 725526, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weekday', models.IntegerField(default=0)),
                ('color', models.CharField(choices=[('R', 'Red'), ('O', 'Orange'), ('G', 'Green')], default='G', max_length=7)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binnetapp.bin')),
            ],
        ),
    ]
