# Generated by Django 5.0.2 on 2024-04-04 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binnetapp', '0013_remove_bin_color_alter_measurement_measuredate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='fillrate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='measureDate',
            field=models.DateField(default=datetime.datetime(2024, 4, 4, 12, 48, 32, 58603, tzinfo=datetime.timezone.utc)),
        ),
    ]
